#ifndef OPEN_AICG2_PLUS_MACRO_HPP
#define OPEN_AICG2_PLUS_MACRO_HPP

#define OPENAICG2PLUS_EXPAND_OPTION_STR(option) OPENAICG2PLUS_EXPAND_OPTION_STR_(option)
#define OPENAICG2PLUS_EXPAND_OPTION_STR_(option) #option

#endif // OPEN_AICG2_PLUS_MACRO_HPP
